name: dev

on:
  push:
    branches:
      - 'Dev_FB'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - run: rm -rf $GITHUB_WORKSPACE/*
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm ci
            - run: npm run lint
            - run: rm -rf $GITHUB_WORKSPACE/*
    log-check:
        runs-on: ubuntu-latest
        steps:
            - run: rm -rf $GITHUB_WORKSPACE/*
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Required to fetch all history for diff
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Fail on checked-in console.log
              run: |
                set -euo pipefail
                # Get the list of files changed in the last commit
                changed_files=$(git diff --name-only HEAD^ HEAD)

                # Loop through each changed file
                while IFS= read -r file; do
                  # Get the diff for the current file
                  diff=$(git diff HEAD^ HEAD -- "$file")

                  # Extract only the added lines from the diff
                  added_lines=$(echo "$diff" | grep '^+[^+]' | cut -c2-)

                  # Search for console.log in the added lines
                  matches=$(echo "$added_lines" | grep -nH -E "console\.log\s*\(")

                  # If matches are found, print the error and exit
                  if [ -n "$matches" ]; then
                    echo "ERROR: console.log usages found in checked-in file $file:"
                    echo "$matches"
                    exit 1
                  fi
                done <<< "$changed_files"
            - run: rm -rf $GITHUB_WORKSPACE/*
    build:
        runs-on: ubuntu-latest
        needs: 
          - lint
          - log-check
        steps:
            - run: rm -rf $GITHUB_WORKSPACE/*
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm ci
            - run: npm run build
            - run: rm -rf $GITHUB_WORKSPACE/*